language: java
jdk:
- oraclejdk8
before_script:
- psql -c 'create database chemistry;' -U postgres
deploy:
  provider: heroku
  app:
    staging: attriclasses
  api_key:
    secure: qwme4MRqt0Cb2P9VEhho7sgO/osX5WWKcCGNvyH8O2Ys5KP5kd0ND7gR26+53KdoHwtNvLOdymU0J75MV37ko7Z7LuJJgzcOh6Jtydwzd79l0zG+nWyFajHnmeohWwEV1m9UVRCmi+ynBH07XLunYpvsvKj1YKBeURmeL/XPsTtrh73rIvBCia2NO39OdTxYFU73vsgozcTjV0WfJV2ee5ZRUFtqbHxKifyEguYq3XUIGRXdFnc9KHZXuRY0ygAWcjLvUGtraD/m/Gn/Xd7irMUt3UD/oIuvwpNhsv4hEZ0i9EcutprB13bSmY8Dz2eNTbNyz01Qmr0ebJtdhbn4aulstf9uGKZvKenUnaJ6ra99+Vcn5pgBB1yLkRqlGwtgCqvniOX1JkN16IkLkuNokA0GgtqwQbLWESkc+iFBdOmDcgP+E7ByFJilqEqB8bJ0trQB23X5mqa2WEn2+UAXdeTa7QdRXgC+9s4yRJ6FOt9gvfBagLPWY2jBn6KYu4djz0kMQZyj/ZLGuzV04oaXljrDlEIBwE6Hmwu1Gsnt2JN5d8d4d+qKPeRVZs9JzRw4YpNrwducAgjHHp0w4wgvUo5x8EMBJccSEHrFiu8WP+Ve2U3PGkBdSHp361SEECpMaH0v5t79cowkqqehsWEYSVJCfVMVR3l4qySiO/VGtPo=
